config/routes.rb
Rails.application.routes.draw do
  resources :meteo_stations
  devise_for :users
  resources :meteos
  resources :users
  root to: 'meteos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meteo.rb
class Meteo < ApplicationRecord
  validates :temperature, :pressure, :humidity, presence: true
end

app/models/meteo_station.rb
class MeteoStation < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :meteo_stations, foreign_key: :user_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meteo_stations_controller.rb
class MeteoStationsController < ApplicationController
  before_action :set_meteo_station, only: [:show, :edit, :update, :destroy]

  # GET /meteo_stations
  # GET /meteo_stations.json
  def index
    @meteo_stations = MeteoStation.all
  end

  # GET /meteo_stations/1
  # GET /meteo_stations/1.json
  def show
  end

  # GET /meteo_stations/new
  def new
    @meteo_station = MeteoStation.new
  end

  # GET /meteo_stations/1/edit
  def edit
  end

  # POST /meteo_stations
  # POST /meteo_stations.json
  def create
    @meteo_station = MeteoStation.new(meteo_station_params)

    respond_to do |format|
      if @meteo_station.save
        format.html { redirect_to @meteo_station, notice: 'Meteo station was successfully created.' }
        format.json { render :show, status: :created, location: @meteo_station }
      else
        format.html { render :new }
        format.json { render json: @meteo_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meteo_stations/1
  # PATCH/PUT /meteo_stations/1.json
  def update
    respond_to do |format|
      if @meteo_station.update(meteo_station_params)
        format.html { redirect_to @meteo_station, notice: 'Meteo station was successfully updated.' }
        format.json { render :show, status: :ok, location: @meteo_station }
      else
        format.html { render :edit }
        format.json { render json: @meteo_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meteo_stations/1
  # DELETE /meteo_stations/1.json
  def destroy
    @meteo_station.destroy
    respond_to do |format|
      format.html { redirect_to meteo_stations_url, notice: 'Meteo station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meteo_station
      @meteo_station = MeteoStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meteo_station_params
      params.fetch(:meteo_station, {})
    end
end

app/controllers/meteos_controller.rb
class MeteosController < ApplicationController
  before_action :set_meteo, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: :create

  # GET /meteos
  # GET /meteos.json
  def index
    @meteos = Meteo.all.order(created_at: :desc)
    @meteo = @meteos.first
  end

  # GET /meteos/1
  # GET /meteos/1.json
  def show
  end

  # GET /meteos/new
  def new
    @meteo = Meteo.new
  end

  # GET /meteos/1/edit
  def edit
  end

  # POST /meteos
  # POST /meteos.json
  def create
    @meteo = Meteo.new(meteo_params)
    respond_to do |format|
      if @meteo.save
        format.html { redirect_to @meteo, notice: 'Meteo was successfully created.' }
        format.json { render json: @meteo, status: :saved }
      else
        format.html { render :new }
        format.json { render json: @meteo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meteos/1
  # PATCH/PUT /meteos/1.json
  def update
    respond_to do |format|
      if @meteo.update(meteo_params)
        format.html { redirect_to @meteo, notice: 'Meteo was successfully updated.' }
        format.json { render :show, status: :ok, location: @meteo }
      else
        format.html { render :edit }
        format.json { render json: @meteo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meteos/1
  # DELETE /meteos/1.json
  def destroy
    @meteo.destroy
    respond_to do |format|
      format.html { redirect_to meteos_url, notice: 'Meteo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meteo
      @meteo = Meteo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meteo_params
      params.require(:meteo).permit(:temperature, :pressure, :humidity)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def update
    user = User.find(params[:id])
    if user == current_user
      user.update(user_params)
    end
    redirect_to action: :show
  end

  private
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meteo_stations_helper.rb
module MeteoStationsHelper
end

app/helpers/meteos_helper.rb
module MeteosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- <a class="navbar-brand" href="#">Navbar</a> -->
  <%= link_to('Meteos', root_path, class:'navbar-brand') %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to('Déconnexion',destroy_user_session_path, class:'nav-link') %>
        <% else %>
          <%= link_to('Connexion', new_user_session_path, class:'nav-link') %>
        <% end %>
      </li>
      <li class="nav-item">
        <% unless user_signed_in? %>
          <%= link_to('Inscription',  new_user_registration_path, class:'nav-link') %>
        <% end %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to('Dashboard', user_path(current_user), class:'nav-link') %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyMeteoApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render('layouts/navbar') %>
    <%= yield %>
  </body>
</html>

app/views/meteo_stations/_form.html.haml
= simple_form_for(@meteo_station) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/meteo_stations/edit.html.haml
%h1 Editing meteo_station

= render 'form'

= link_to 'Show', @meteo_station
\|
= link_to 'Back', meteo_stations_path

app/views/meteo_stations/index.html.haml
%h1 Listing meteo_stations

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @meteo_stations.each do |meteo_station|
      %tr
        %td= link_to 'Show', meteo_station
        %td= link_to 'Edit', edit_meteo_station_path(meteo_station)
        %td= link_to 'Destroy', meteo_station, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Meteo station', new_meteo_station_path

app/views/meteo_stations/new.html.haml
%h1 New meteo_station

= render 'form'

= link_to 'Back', meteo_stations_path

app/views/meteo_stations/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_meteo_station_path(@meteo_station)
\|
= link_to 'Back', meteo_stations_path

app/views/meteos/_form.html.erb
<%= form_with(model: meteo, local: true) do |form| %>
  <% if meteo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meteo.errors.count, "error") %> prohibited this meteo from being saved:</h2>

      <ul>
      <% meteo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meteos/edit.html.erb
<h1>Editing Meteo</h1>

<%= render 'form', meteo: @meteo %>

<%= link_to 'Show', @meteo %> |
<%= link_to 'Back', meteos_path %>

app/views/meteos/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <h1 class="text-center">Meteos</h1>
      <div class="text-center big-text">
        Température : <%= @meteo.temperature / 10.0 %> <br>
        Pression : <%= @meteo.pressure / 100.0 %> <br>
        Humidité : <%= @meteo.humidity %> <br>
      </div>

      <table class=table>
        <thead>
          <tr>
            <th>Température</th>
            <th>Pression</th>
            <th>Humidité</th>
            <th>Date</th>
          </tr>
        </thead>

        <tbody>
          <% @meteos.each do |meteo| %>
            <tr>
              <td><%= meteo.temperature / 10.0 %></td>
              <td><%= meteo.pressure / 100.0 %></td>
              <td><%= meteo.humidity %>%</td>
              <td><%= l(meteo.created_at, format: :short) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/meteos/new.html.erb
<h1>New Meteo</h1>

<%= render 'form', meteo: @meteo %>

<%= link_to 'Back', meteos_path %>

app/views/meteos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_meteo_path(@meteo) %> |
<%= link_to 'Back', meteos_path %>

app/views/users/show.haml
.container-fluid
  .row
    .col-xs-12.col-sm-3.text-center
      %h2.text-center Menu
      %ul.nav.flex-column
        %li.nav-item
          = link_to('Profil', user_path(current_user), class: 'nav-link active')
        %li.nav-item
          = link_to('Stations meteos', '#', class: 'nav-link')
    .col-xs-12.col-sm-9
      = simple_form_for(current_user) do |f|
        = f.input :email
        = f.input :first_name
        = f.input :last_name
        = f.submit